#### Importing Library

In [1]:
import numpy as np

####  Numpy Arrays
* Vectors: 1D Arrays
* Matrices: 2D Array


#### np array vs python list 

* Memory efficient
* Easily expandable to N-dimension
* High speed of calculation.
* Broadcasting operations and function with Numpy
* All major DS, Ml, AI libraries are build on top of numpy.
* 


#### Create Numpy Array and Objects

In [2]:
my_list = [1,2,3]

In [3]:
type(my_list)

list

In [4]:
# Convert above list to numpy array:
arr = np.array(my_list) # Remember this is class.method(parameter) 
arr

array([1, 2, 3])

In [5]:
type(arr)

numpy.ndarray

In [6]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
# converting to numpy array 
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
# how to know the dimension of numpy array? 
# Count the number of square brackets. 


#### How to create an array using built in methods: 


In [9]:
#1. arange: it will return evenly spaced values with in given interval 
np.arange(0,10)  # or # np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(3,79,7)

array([ 3, 10, 17, 24, 31, 38, 45, 52, 59, 66, 73])

In [11]:
# zeros 
np.zeros(4)

array([0., 0., 0., 0.])

In [12]:
np.zeros((3,4)) # create zeros of three rows and 4 coloumns

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
#ones 
np.ones(2)

array([1., 1.])

In [14]:
np.ones((3,5)) # rows and coloumns 

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [15]:
np.ones((3,5,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [16]:
# linspace : return evenely spaced numbers over the specified interval 
np.linspace(11,80,15) # here, 5 evenley space numbers including 11 an 18. 

array([11.        , 15.92857143, 20.85714286, 25.78571429, 30.71428571,
       35.64285714, 40.57142857, 45.5       , 50.42857143, 55.35714286,
       60.28571429, 65.21428571, 70.14285714, 75.07142857, 80.        ])

In [17]:
np.arange(11,80,15)

array([11, 26, 41, 56, 71])

In [18]:
#eye : creates an identity matrix 
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

#### random # module within numpy array

In [19]:
#rand : it will creates an array of given shape and populates it random sample from a uniform distribution over [0,1)
# What is uniform distribution?

In [20]:
np.random.rand(6)  # or u have to import random as rand
# it dgives uniform  distribution btwn [0,1) # i is not included 

array([0.91259297, 0.945345  , 0.06935252, 0.7751256 , 0.66569647,
       0.70020964])

In [21]:
np.random.rand(4,5)

array([[0.81575829, 0.02023353, 0.1573263 , 0.53941232, 0.48626449],
       [0.63139824, 0.33696495, 0.7421717 , 0.65163932, 0.16406142],
       [0.77724279, 0.39538399, 0.85338274, 0.52751407, 0.93017164],
       [0.49576138, 0.53359053, 0.09358275, 0.01608247, 0.53966042]])

In [22]:
# randn --> random normal
# it return samples from the "standar normal" distribution(sigma = 1) 
np.random.randn(6)

array([-2.22782098,  0.03967975, -2.14791694,  0.80600268, -3.34971828,
        0.10447986])

In [23]:
np.random.randn(3,2)

array([[-0.94271037,  1.58207432],
       [-0.68125966,  1.7099161 ],
       [ 0.57325345,  0.84752271]])

### Have alook at the Numpy documentation

In [24]:
num = np.arange(1,10,0.25)
num

array([1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 , 2.75, 3.  , 3.25, 3.5 ,
       3.75, 4.  , 4.25, 4.5 , 4.75, 5.  , 5.25, 5.5 , 5.75, 6.  , 6.25,
       6.5 , 6.75, 7.  , 7.25, 7.5 , 7.75, 8.  , 8.25, 8.5 , 8.75, 9.  ,
       9.25, 9.5 , 9.75])

In [25]:
# randominteger: randint
# returns random interger from low(inclusive) to high(exclusive) 
np.random.randint(1,6)

4

In [26]:
np.random.randint(1,100,50) # 50 numbers between [1,100)

array([ 3, 17, 76, 46, 11, 93, 24, 51, 40, 58, 73, 97, 20, 96, 70, 82, 15,
       93, 69, 32, 70, 79,  3, 18, 43, 64, 41, 81, 31, 66, 90, 94, 21, 33,
       80, 54, 63, 17, 27, 99, 32,  8, 62, 87, 63, 73, 26, 73, 23, 88])

In [27]:
# to regenerate the same random set of number: use seed

#### seed

In [28]:
np.random.seed(50) # this 50 is like a set A i question paper. 
np.random.randint(1,100,50)

array([49, 97, 12, 34, 95,  5, 71, 71, 23,  6,  3, 96, 72, 69, 79, 36, 93,
       92, 27, 91,  7, 21, 44, 32, 50, 86, 42, 65,  7, 20,  3, 80, 31, 36,
       27, 61, 67, 77, 97, 68,  3, 11, 52,  1, 94, 94, 95,  1, 12, 31])

In [29]:
np.random.seed(51) # this 51 is like a set b in question paper. 
np.random.randint(1,100,50)

array([58, 97, 74, 70, 17, 22, 95, 53, 38, 38, 61, 95, 29, 85, 37, 36, 28,
       29, 43, 11,  7, 26, 34, 78, 40, 49, 25, 41, 55, 78, 29, 70, 58, 19,
       64, 76, 68, 95, 88,  8, 68, 92, 62, 35, 54, 31, 56, 18, 68,  9])

In [30]:
np.random.seed(50) # this 50 is like a set A i question paper. 
np.random.randint(1,100,50)

array([49, 97, 12, 34, 95,  5, 71, 71, 23,  6,  3, 96, 72, 69, 79, 36, 93,
       92, 27, 91,  7, 21, 44, 32, 50, 86, 42, 65,  7, 20,  3, 80, 31, 36,
       27, 61, 67, 77, 97, 68,  3, 11, 52,  1, 94, 94, 95,  1, 12, 31])

In [31]:
# What can be the largest number i can use in this : np.random.seed(2^32-1)   # depends on pc. 

#### Array attributes and methos

In [32]:
arr = np.arange(25) # 25 elem from zero 
ranar = np.random.randint(0,50,10)

In [33]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [34]:
ranar

array([26,  7, 28, 24, 27, 46, 13,  7, 36, 36])

In [35]:
#reshape: it returns an array with same data with new shape. 

In [36]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [37]:

ranar.reshape(2,5)

array([[26,  7, 28, 24, 27],
       [46, 13,  7, 36, 36]])

In [38]:
#max  and  min 

In [39]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [40]:
ranar

array([26,  7, 28, 24, 27, 46, 13,  7, 36, 36])

In [41]:
ranar.max()

46

In [42]:
ranar.min()

7

In [43]:
# to get the index of where the max was. : argmin / argmax 
ranar.argmax()

5

In [44]:
ranar.argmin()

1

In [45]:
# shape :      this is an attribute: it have no scope of input 
# Eg: 
ranar.shape


(10,)

In [46]:
arr.shape

(25,)

In [47]:
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [48]:
matrix =         np.array(my_matrix)
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [49]:
matrix.shape

(3, 3)

In [50]:
arr 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [51]:
ranar

array([26,  7, 28, 24, 27, 46, 13,  7, 36, 36])

In [52]:
arr_1_25 = arr.reshape(1,25) #n 1 row 25 col 
arr_1_25

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [53]:
arr_25_1 = arr.reshape(25,1) # 25 row, 1 col
arr_25_1

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [54]:
arr.shape

(25,)

In [55]:
arr_1_25.shape

(1, 25)

In [56]:
arr_25_1.shape

(25, 1)

In [57]:
# Note dont confues btw arr(this is 1) and arr_1_25, arr_25_1 (this is 2D)

In [58]:
arr # this is 1D. 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [59]:
arr_1_25 # this is two D

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])