In [1]:
import numpy as np

In [2]:
arr = np.arange(20,71,3)

In [3]:
arr


array([20, 23, 26, 29, 32, 35, 38, 41, 44, 47, 50, 53, 56, 59, 62, 65, 68])

In [4]:
type(arr)

numpy.ndarray

### Bracket indexing and selection

In [5]:
arr[4] # grab the element at index4

32

In [6]:
arr[-3]

62

In [7]:
# Get a velues in arrange 
arr[2:7] # note 7 is not included

array([26, 29, 32, 35, 38])

In [8]:
arr[0:1]

array([20])

### Broadcasting function (property)

In [9]:
arr

array([20, 23, 26, 29, 32, 35, 38, 41, 44, 47, 50, 53, 56, 59, 62, 65, 68])

In [10]:
# i want to set a value using index range(bhroadcasting) 
arr[0:5] = 100

In [11]:
arr

array([100, 100, 100, 100, 100,  35,  38,  41,  44,  47,  50,  53,  56,
        59,  62,  65,  68])

# doing it by list 
To do something similar with a Python list:

You cannot assign a single value directly to a slice like NumPy (broadcasting), but you can do it using slicing and repetition:m

In [12]:
lst = list(range(20, 71, 3))
lst[0:5] = [100] * 5  # Replace first 5 elements with 100
print(lst)


[100, 100, 100, 100, 100, 35, 38, 41, 44, 47, 50, 53, 56, 59, 62, 65, 68]


Summary:

    NumPy allows broadcasting: arr[0:5] = 100

    Python lists need explicit repetition: lst[0:5] = [100] * 5

In [13]:
slice_of_array = arr[0:5]

In [14]:
slice_of_array[:] = 99 # grab everything

In [15]:
arr

array([99, 99, 99, 99, 99, 35, 38, 41, 44, 47, 50, 53, 56, 59, 62, 65, 68])

In [16]:
# note it will change the original array arr 
# because this operation slice_of_array = arr[0:5] data is not copied, it is view of the original arry



In [17]:
l1   = [1,2,3,4,5,6,7,8,9,10]

In [18]:
l2 = l1[0:5]

In [19]:
#l2[:] = 34  This way u cant do in list  
#l1[0:5] = [99]*5
l2[0] = 99

In [20]:
l2

[99, 2, 3, 4, 5]

In [21]:
l1 #  note:: l1 wont change if use list, but in array it changes the original array***

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [22]:
arr = np.arange(20,71,3)

In [23]:
sub_array = arr[0:3]

In [24]:
sub_array

array([20, 23, 26])

In [25]:
# how to make sure, the changes iam making to sub arry wont shange the arr. 

In [26]:
sub_array[0:3]= 10

In [27]:
sub_array

array([10, 10, 10])

In [28]:
arr

array([10, 10, 10, 29, 32, 35, 38, 41, 44, 47, 50, 53, 56, 59, 62, 65, 68])

In [29]:
# to get the copy of an array we need tpo explicitly mention
arr = np.arange(20,71,3)

In [30]:
arr_copy = arr.copy() # this is to make a copy of array, rather than  viewing

In [31]:
arr_copy[0:5] = 10

In [32]:
arr_copy

array([10, 10, 10, 10, 10, 35, 38, 41, 44, 47, 50, 53, 56, 59, 62, 65, 68])

In [33]:
arr

array([20, 23, 26, 29, 32, 35, 38, 41, 44, 47, 50, 53, 56, 59, 62, 65, 68])

###  Indexing of 2D( matrices )

In [34]:
arr_2D = np.arange(0,9).reshape(3,3)
arr_2D

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [35]:
# say i want to  grab a row: 
arr_2D[1] # to grab 2nd row


array([3, 4, 5])

In [36]:
arr_2D[-2]

array([3, 4, 5])

In [37]:
arr_2D[1][0]

3

In [38]:
arr_2D[-2][-1]


5

In [39]:
arr

array([20, 23, 26, 29, 32, 35, 38, 41, 44, 47, 50, 53, 56, 59, 62, 65, 68])

In [40]:
len(arr)

17

In [41]:
np.random.seed(50)
demo_arr = np.random.randint(1,100,(5,6))
demo_arr

array([[49, 97, 12, 34, 95,  5],
       [71, 71, 23,  6,  3, 96],
       [72, 69, 79, 36, 93, 92],
       [27, 91,  7, 21, 44, 32],
       [50, 86, 42, 65,  7, 20]])

In [42]:
# grab 71 and 36 
Val1  = demo_arr[1][0]
Val2 = demo_arr[-3][-3]

In [43]:
print(Val1)
print(Val2)

71
36


In [44]:
# other way is 
Val3  = demo_arr[1, 1]

In [45]:
print(Val3)

71


In [46]:
demo_arr[2][3]

36

### Slicing 


In [47]:
demo_arr

array([[49, 97, 12, 34, 95,  5],
       [71, 71, 23,  6,  3, 96],
       [72, 69, 79, 36, 93, 92],
       [27, 91,  7, 21, 44, 32],
       [50, 86, 42, 65,  7, 20]])

In [48]:
demo_arr[1:4] # 4 is not included 

array([[71, 71, 23,  6,  3, 96],
       [72, 69, 79, 36, 93, 92],
       [27, 91,  7, 21, 44, 32]])

In [49]:
demo_arr[1:4, -3:-1] # do this using comma

array([[ 6,  3],
       [36, 93],
       [21, 44]])

In [50]:
demo_arr

array([[49, 97, 12, 34, 95,  5],
       [71, 71, 23,  6,  3, 96],
       [72, 69, 79, 36, 93, 92],
       [27, 91,  7, 21, 44, 32],
       [50, 86, 42, 65,  7, 20]])

In [51]:
demo_arr[:3]

array([[49, 97, 12, 34, 95,  5],
       [71, 71, 23,  6,  3, 96],
       [72, 69, 79, 36, 93, 92]])

In [52]:
demo_arr[:2, 0:2]

array([[49, 97],
       [71, 71]])

In [53]:
demo_arr[3:,-2:]

array([[44, 32],
       [ 7, 20]])

In [54]:
demo_arr[1:3,2:4]

array([[23,  6],
       [79, 36]])

###  Conditional Selection in Numpy

In [56]:
arr = np.arange(1,11)

In [57]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [58]:
type(arr)

numpy.ndarray

In [59]:
arr + 3

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [61]:
arr > 2

array([False, False,  True,  True,  True,  True,  True,  True,  True,
        True])

In [68]:
bool_arr = arr >3


In [69]:
bool_arr


array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [64]:
arr[bool_arr == True]

array([ 4,  5,  6,  7,  8,  9, 10])

In [70]:
arr[arr>3]

array([ 4,  5,  6,  7,  8,  9, 10])

In [71]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [72]:
arr[bool_arr == False]

array([1, 2, 3])

In [73]:
arr[bool_arr]

array([ 4,  5,  6,  7,  8,  9, 10])

In [74]:
arr[arr < 3]

array([1, 2])

In [75]:
arr[arr < 6]

array([1, 2, 3, 4, 5])

### Numpy Operation

In [77]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [78]:
arr + arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [79]:
arr * arr

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [80]:
arr/arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [81]:
1/arr

array([1.        , 0.5       , 0.33333333, 0.25      , 0.2       ,
       0.16666667, 0.14285714, 0.125     , 0.11111111, 0.1       ])

In [82]:
arr ** 0.5

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

### Universal array function in Numpy (ufuncs)

In [83]:
# square root 
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

In [84]:
#exponential 
np.exp(arr)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04])

In [85]:
# Sin 
np.sin(arr)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111])

In [86]:
# log
np.log(arr)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509])

In [87]:
# have alook at ufuncns Documentation

In [88]:
np.log10(arr)

array([0.        , 0.30103   , 0.47712125, 0.60205999, 0.69897   ,
       0.77815125, 0.84509804, 0.90308999, 0.95424251, 1.        ])

In [89]:
np.deg2rad(arr)

array([0.01745329, 0.03490659, 0.05235988, 0.06981317, 0.08726646,
       0.10471976, 0.12217305, 0.13962634, 0.15707963, 0.17453293])

In [92]:
np.rad2deg(np.pi/2)

90.0

###  Summary Statics in Arrays 


In [99]:
arr = np.arange(10,20)

In [100]:
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [101]:
arr.sum()

145

In [102]:
arr.mean()

14.5

In [103]:
arr.max()

19

In [104]:
arr.min()

10

In [106]:
# Index number 
arr.argmax()

9

In [107]:
arr.argmin()

0

In [108]:
arr.var()

8.25

In [109]:
arr.std()

2.8722813232690143

### Axis logic

* axis 0  : Vertical Axis( rows)
* axis 1  : Horizontal axis (columns)


In [121]:
np.random.seed(50)
arr_2d = np.random.randint(10,99,(3,4)) # dim 3 rows 4 col 

In [126]:
arr_2d

array([[58, 21, 43, 14],
       [80, 80, 32, 15],
       [12, 81, 78, 88]])

In [127]:
arr_2d.sum()

602

In [128]:
arr_2d.sum(axis = 0)

array([150, 182, 153, 117])

In [130]:
arr_2d.sum(axis = 1)

array([136, 207, 259])