In [1]:
import numpy as np


In [2]:
np.random.seed(40)

In [6]:
mat =  np.arange(1,43).reshape(6,7)

In [7]:
mat

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28],
       [29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42]])

In [13]:
# Q1 
# Reshape this to 7 rows and 6 col
MAT = np.arange(1,43).reshape(7,6)
MAT


array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36],
       [37, 38, 39, 40, 41, 42]])

In [18]:
# Q2 Grab 33 and 24

print(MAT[5,2])
print(MAT[3,-1])



33
24


In [21]:
mat

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28],
       [29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42]])

In [26]:
#Q3 Grab array [[24, 25, 26]],[[31,32,33]]
mat[3:5, 2:5]



array([[24, 25, 26],
       [31, 32, 33]])

In [29]:
# calculate standard deviation 
# row-wise, colwise, over all
mat.std(axis = 0)

array([11.95477589, 11.95477589, 11.95477589, 11.95477589, 11.95477589,
       11.95477589, 11.95477589])

In [30]:
mat.std(axis = 1)

array([2., 2., 2., 2., 2., 2.])

In [31]:
mat.std()

12.120918557051139