####  Just for Understanding.

In [145]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt


In [146]:
with open('One.txt') as mytext:
    print(mytext.read())

This is a story about dogs
our canine pets
Dogs are furry animals



In [147]:
with open('Two.txt') as mytext:
    print(mytext.read())

This story is about surfing
Catching waves is fun
Surfing is a popular water sport



### Reading entire text as a string:

In [148]:
with open('One.txt') as mytext:
    entire_text = mytext.read()

In [149]:
entire_text

'This is a story about dogs\nour canine pets\nDogs are furry animals\n'

###  Read each lines as a list:

In [150]:
with open('One.txt') as mytext:
   lines = mytext.readlines()

In [151]:
lines

['This is a story about dogs\n',
 'our canine pets\n',
 'Dogs are furry animals\n']

###  Or 
* Building a vocabulary (creating a bag of words )

In [152]:
with open('One.txt') as mytext:
    words_one = mytext.read().lower().split()

In [153]:
words_one

['this',
 'is',
 'a',
 'story',
 'about',
 'dogs',
 'our',
 'canine',
 'pets',
 'dogs',
 'are',
 'furry',
 'animals']

In [154]:
len(words_one)

13

In [155]:
unique_words_one = set(words_one)

In [156]:
unique_words_one

{'a',
 'about',
 'animals',
 'are',
 'canine',
 'dogs',
 'furry',
 'is',
 'our',
 'pets',
 'story',
 'this'}

In [157]:
with open('Two.txt') as mytext:
    words_two = mytext.read().lower().split()

In [158]:
words_two

['this',
 'story',
 'is',
 'about',
 'surfing',
 'catching',
 'waves',
 'is',
 'fun',
 'surfing',
 'is',
 'a',
 'popular',
 'water',
 'sport']

In [159]:
len(words_two)

15

In [160]:
unique_words_two = set(words_two)

In [161]:
unique_words_two

{'a',
 'about',
 'catching',
 'fun',
 'is',
 'popular',
 'sport',
 'story',
 'surfing',
 'this',
 'water',
 'waves'}

### Get all unique word :

In [162]:
all_uni_words = set()
all_uni_words.update(unique_words_one)

In [163]:
all_uni_words.update(unique_words_two)

In [164]:
all_uni_words

{'a',
 'about',
 'animals',
 'are',
 'canine',
 'catching',
 'dogs',
 'fun',
 'furry',
 'is',
 'our',
 'pets',
 'popular',
 'sport',
 'story',
 'surfing',
 'this',
 'water',
 'waves'}

### Assigning numbers for each of this unique words:

In [165]:
full_vocabulary = dict()
i = 0 
for w in all_uni_words:
    full_vocabulary[w] = i
    i = i + 1

In [166]:
full_vocabulary

{'are': 0,
 'popular': 1,
 'fun': 2,
 'animals': 3,
 'catching': 4,
 'this': 5,
 'about': 6,
 'surfing': 7,
 'water': 8,
 'furry': 9,
 'waves': 10,
 'is': 11,
 'our': 12,
 'story': 13,
 'a': 14,
 'sport': 15,
 'pets': 16,
 'canine': 17,
 'dogs': 18}

###  Bag of words to Frequency Counts:

In [167]:
one_freq= [0]*len(full_vocabulary)
two_freq= [0]*len(full_vocabulary)
all_words = ['']*len(full_vocabulary) # bunch of wmpty string 

In [168]:
for w in full_vocabulary:
    w_ind = full_vocabulary[w] # calling by key 
    all_words[w_ind] = w

In [169]:
all_words

['are',
 'popular',
 'fun',
 'animals',
 'catching',
 'this',
 'about',
 'surfing',
 'water',
 'furry',
 'waves',
 'is',
 'our',
 'story',
 'a',
 'sport',
 'pets',
 'canine',
 'dogs']

In [170]:
#full_vocabulary

In [171]:
one_freq

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [172]:
one_text

['this',
 'is',
 'a',
 'story',
 'about',
 'dogs',
 'our',
 'canine',
 'pets',
 'dogs',
 'are',
 'furry',
 'animals']

In [173]:
full_vocabulary

{'are': 0,
 'popular': 1,
 'fun': 2,
 'animals': 3,
 'catching': 4,
 'this': 5,
 'about': 6,
 'surfing': 7,
 'water': 8,
 'furry': 9,
 'waves': 10,
 'is': 11,
 'our': 12,
 'story': 13,
 'a': 14,
 'sport': 15,
 'pets': 16,
 'canine': 17,
 'dogs': 18}

In [174]:
# add in the count per word in the doc 

with open('One.txt') as f:
    one_text = f.read().lower().split()  # list 


for w in one_text:
    w_ind = full_vocabulary[w]
    one_freq[w_ind] += 1
    

In [175]:
one_freq


[1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 2]

In [176]:
# add in the count per word in the doc 

with open('Two.txt') as f:
    two_text = f.read().lower().split()  # list 


for w in two_text:
    w_ind = full_vocabulary[w]
    two_freq[w_ind] += 1
    

In [177]:
two_freq

[0, 1, 1, 0, 1, 1, 1, 2, 1, 0, 1, 3, 0, 1, 1, 1, 0, 0, 0]

In [180]:
pd.DataFrame(data = [one_freq, two_freq], columns = all_words)

,are,popular,fun,animals,catching,this,about,surfing,water,furry,waves,is,our,story,a,sport,pets,canine,dogs
0,1,0,0,1,0,1,1,0,0,1,0,1,1,1,1,0,1,1,2
1,0,1,1,0,1,1,1,2,1,0,1,3,0,1,1,1,0,0,0


In [181]:
one_freq # this comes as row one 

[1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 2]

In [185]:
two_freq # this comes as row two 

[0, 1, 1, 0, 1, 1, 1, 2, 1, 0, 1, 3, 0, 1, 1, 1, 0, 0, 0]

In [186]:
all_words

['are',
 'popular',
 'fun',
 'animals',
 'catching',
 'this',
 'about',
 'surfing',
 'water',
 'furry',
 'waves',
 'is',
 'our',
 'story',
 'a',
 'sport',
 'pets',
 'canine',
 'dogs']

###  Feature Extraction with sklearn.


In [187]:
text = ["This is a line",
        "This is another line",
        "Completely different line"
       ]


In [188]:
from sklearn.feature_extraction.text import TfidfTransformer, TfidfVectorizer, CountVectorizer

In [189]:
cv = CountVectorizer()

In [190]:
cv.fit_transform(text)

<3x6 sparse matrix of type '<class 'numpy.int64'>'
	with 10 stored elements in Compressed Sparse Row format>

In [192]:
sp_mat = cv.fit_transform(text)

In [194]:
sp_mat.todense()

matrix([[0, 0, 0, 1, 1, 1],
        [1, 0, 0, 1, 1, 1],
        [0, 1, 1, 0, 1, 0]])

In [196]:
cv.vocabulary_  # note here a is not there, since it is common word

{'this': 5, 'is': 3, 'line': 4, 'another': 0, 'completely': 1, 'different': 2}

In [200]:
cv =  CountVectorizer(stop_words= 'english') # to ignore more stop words. 

In [201]:
cv.fit_transform(text).todense()

matrix([[0, 0, 1],
        [0, 0, 1],
        [1, 1, 1]])

In [202]:
cv.vocabulary_

{'line': 2, 'completely': 0, 'different': 1}

### Tfidf:

In [203]:
# Tfidf transformer 
tfidf_transformer = TfidfTransformer()


In [204]:
cv = CountVectorizer()

In [205]:
counts = cv.fit_transform(text)

In [206]:
counts

<3x6 sparse matrix of type '<class 'numpy.int64'>'
	with 10 stored elements in Compressed Sparse Row format>

In [207]:
cv.vocabulary_

{'this': 5, 'is': 3, 'line': 4, 'another': 0, 'completely': 1, 'different': 2}

In [209]:
tfidf = tfidf_transformer.fit_transform(counts)

In [212]:
tfidf.todense() # This gives the weights of the words. 

matrix([[0.        , 0.        , 0.        , 0.61980538, 0.48133417,
         0.61980538],
        [0.63174505, 0.        , 0.        , 0.4804584 , 0.37311881,
         0.4804584 ],
        [0.        , 0.65249088, 0.65249088, 0.        , 0.38537163,
         0.        ]])

### Todo it in two steps:

In [218]:
text

['This is a line', 'This is another line', 'Completely different line']

In [216]:
tfidf = TfidfVectorizer() 
new  = tfidf.fit_transform(text) 

In [217]:
new.todense()

matrix([[0.        , 0.        , 0.        , 0.61980538, 0.48133417,
         0.61980538],
        [0.63174505, 0.        , 0.        , 0.4804584 , 0.37311881,
         0.4804584 ],
        [0.        , 0.65249088, 0.65249088, 0.        , 0.38537163,
         0.        ]])